
server:
  port: 9999

spring:
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234@abcd

  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234@abcd
    url: jdbc:mysql://localhost:3306/vue_login?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf-8&connectTimeout=30000&socketTimeout=60000
